### ISSUE TITLE
Missing journal mount path

### ISSUE THREAD

**Issue by sazo** [solarwinds/fluentd-deployment#9]
I was getting a lot of errors when deploying your kubernetes template.

```
2018-11-05 09:50:07 +0000 [warn]: #0 Systemd::JournalError: No such file or directory retrying in 1s
```

Fixed it with adding missing mount paths

```
volumeMounts:
        - name: journal
          mountPath: /var/log/journal
          readOnly: true

volumes:
      - name: journal
        hostPath:
          path: /run/log/journal
```
